version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - php
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: birdboard
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", '/var/www/html/artisan']
    networks:
      - laravel

  react:
    build:
      context: .
      dockerfile: react.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./lc-react/src:/app/src
    environment:
     - WATCHPACK_POLLING=true
    networks:
      - laravel

networks:
  laravel:
volumes:
  mysql_data:
